//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie2
    {
        public int id { get; set; }
        public string title { get; set; }
        public string coverImg { get; set; }
        public string releaseDate { get; set; }
        public string genre { get; set; }
        public Nullable<int> duration { get; set; }
        public string createDate { get; set; }
        public string modifyDate { get; set; }
    }
}
